### PR TITLE
Capture Escape key presses to close the modal.

### PR DESCRIPTION
**Pull request by goodisontoffee**

### CODE REVIEW

**Comment by goodisontoffee** [comment]
Another attempt to resolve #67, it still uses javascript. Still pretty new to Blazor so unsure if a better approach exists. I've learnt some stuff put this together, hopefully it helps you out :)

**Comment by chrissainty** [comment]
Thanks for submitting this @goodisontoffee. I'm still in two minds about how to implement this. Leave it with me.

**Comment by goodisontoffee** [comment]
No problem @chrissainty, I didn't see the other conversation on the older PR until I'd already done the work ;). What is the reason behind not being keen on the use of javascript? No judgement, just curious.

**Comment by chrissainty** [comment]
To be honest, at this point I think it's probably pride more than anything. We've been able to get this far without JS but maybe it's time to accept it.

**Comment by goodisontoffee** [comment]
Understandable. Maybe leave the feature on ice until it’s either pressing or there is another reason to incorporate js? Bumping the major version for just this might not be worth it. Based on this, would you include a css and js content file with new components you make, just to allow the extensibility point without semver implications?

**Comment by chrissainty** [comment]
I agree this feature wouldn't be enough on its own to warrant a major version bump. 

> Based on this, would you include a css and js content file with new components you make, just to allow the extensibility point without semver implications?

That's an interesting question. I don't think I would. If a blank JS file was included then I wouldn't want to tell developers to reference it in their apps for obvious reasons. So if a feature was then added which used JavaScript, they would have to update their code to reference the JS file anyway. Does that make sense?

**Pull request closed without merging**
