### PR TITLE
Able to optionally set focus to first element to false

### PR DESCRIPTION
**Pull request by David-Moreira**
Hello,
I am a user of your library. I had a use case, where I needed to disable the auto focus to the first element. 
I figure not everyone would like that to happen. Added boolean FocusFirstElement to the options. Left auto focus as default.

Keep up the good work Chris!

### CODE REVIEW

**Comment by chrissainty** [comment]
Thanks for the PR @David-Moreira. The auto focus is part of a wider feature called a focus trap, which makes the modal more accessible for users who potentially can see or use a mouse. 

I guess some people don't need to worry about accessibility in there apps so having the ability to turn this off might be a good idea.

**Comment by David-Moreira** [comment]
Yea, got it Chris! I left the defaults unchanged!
My use case, was actually that I am wrapping a grid inside the modal, and the grid has some text fields to apply filtering to the grid, and these are the first focusable elements that actually come up. And in this case, I don't want them focused by default. 
The idea is great, but It's "opinated", I think it's helpfull to let people turn it off, if they'd like.

On another note, I noticed the grid doesn't really support overflow with the default css (ability to scroll when too much information), I made some overriding tiny changes to your css to make it support. May I raise a PR for that?  Would you like an issue raised?

**Comment by larsk2009** [comment]
First of all, I think this is a nice option to add @David-Moreira! 

However, this PR also seems to change a lot of stuff which has nothing to do with the option mentioned. Personally I find it easier to understand if this PR only changes things for the option, and a different PR is made for the formatting and naming changes. That way the PR is easier to review and it is easier to trace back when something was changed later. But again, that is just my opinion so if @chrissainty is fine with it like this, than no problem 😉. 

As for you question about overflow with css, have a look at these issues: #157 #35. Going from those issues, I think it is by design that the overflow is hidden by default, and the user of the modal should add this themselves if required.

**Comment by David-Moreira** [comment]
Hello lars, 
There's only one commit for this PR, the first one. I committed something else by mistake. I'll clean up once I'm back on my computer.

**Comment by David-Moreira** [comment]
Fixed, thanks for noticing.

**Review by chrissainty — APPROVED** [review]
Thanks for adding this feature @David-Moreira and, as always, thanks for the great observations @larsk2009!

**Pull request merged**
