### PR TITLE
allow pass onClose to show method

### PR DESCRIPTION
**Pull request by troepolik**
this feachure free user from unsubscribe from onClose  event

### CODE REVIEW

**Comment by troepolik** [comment]
any negative comments ?

**Comment by chrissainty** [comment]
Apologies @troepolik. I'm currently going through a very busy period at work and I've just not had time to deal with this yet. I will look at this as soon as I can.

**Comment by troepolik** [comment]
resolved conflicts
fixed null reference exception when you dont pass options parameter

**Comment by chrissainty** [comment]
Closing in favour of #106

**Pull request closed without merging**
