### PR TITLE
Update to .net 6

### LINKED ISSUE #358: [Feature] .NET6
I'm making this issue to track anything related to .NET 6.

- [ ] Update library to .NET 6
- [ ] Make migration guide (if needed)

### PR DESCRIPTION
**Pull request by larsk2009**
Seems to me this is the only thing necessary for using .NET 6? Otherwise this is atleast a starting point. Resolves #358.

It builds on my machine so the error is mostlikely only because the SDK used on the agent is still using .NET 5.x

### CODE REVIEW

**Comment by chrissainty** [comment]
I'm thinking that now might be the time to move to collocated JS files and JS modules. That way, developers will no longer need to reference the JS file in the host page. We could also think about scoped CSS as well. This could really simplify the installation process. 

What do you think, @larsk2009?

**Comment by larsk2009** [comment]
Yes for sure! I can have look when I have time.

**Review by alensweepr — APPROVED** [review]
very nice

**Review by alensweepr — APPROVED** [review]

**Comment by MrGeneric** [comment]
Hey, just curious if there is a release planned with this .net 6 update anytime soon? Thanks for the hard work!

**Comment by larsk2009** [comment]
Well the .net6 part is not so difficult, but I tried to move to collocated JS files/modules and had some issues there, but I don't remember anymore what exactly.

**Comment by chrissainty** [comment]
@larsk2009 Thanks for your initial work on this PR. I've adding in nullable reference types and implicit usings, as per the standard in .NET 6 projects. I've also removed all of the JavaScript as I have a plan to replace the focus trap with a Blazor native version. Something I'll do in another PR to try and keep some tidiness.

**Comment by larsk2009** [comment]
@chrissainty sounds like a great idea! I've not really been using Blazor in general much anymore lately, so didn't have much time to work on this anymore. Really appreciate you picking up this .net6 stuff!

**Pull request merged**
