### PR TITLE
Change FocusFirstElement to ActivateFocusTrap

### LINKED ISSUE #287: [Bug] FocusFirstElement
**Describe the bug**
`FocusFirstElement` also disables the FocusTrap

**To Reproduce**
-

**Expected behavior**
Either we should rename FocusFirstElement, accept the there is some (desirable) side effect to the setting, or add a separate setting to enable or disable the FocusTrap.

### PR DESCRIPTION
**Pull request by larsk2009**
This PR should fix #287.

### CODE REVIEW

**Review by chrissainty — APPROVED** [review]

**Comment by chrissainty** [comment]
@larsk2009 This all looks great. Just before we merge it, are there any demos or readme which needs updating?

**Comment by larsk2009** [comment]
> @larsk2009 This all looks great. Just before we merge it, are there any demos or readme which needs updating?

It has been some time since I made this PR so I am not sure. Hopefully I can check today or tomorrow if anything needs updating.

**Comment by larsk2009** [comment]
I just had a look and I don't think there are any extra updates necessary. I searched the whole solution for `FocusFirstElement` and couldn't find any matches so I think we can merge this.

**Comment by larsk2009** [comment]
@chrissainty I think this can be merged.

**Pull request merged**
