### PR TITLE
Modal template

### PR DESCRIPTION
**Pull request by dfkeenan**
Added the ability to set a template for the Modal using a template in the `BlazoredModal` component. Like so:

```xml
<BlazoredModal>
    <ModalTemplate>
        <div class="modal-backdrop fade show" @onclick="context.Cancel"></div>
        <div class="modal fade show d-block" style="pointer-events: none;" tabindex="-1" role="dialog">
            <div class="modal-dialog " role="document">
                <div class="modal-content border-warning">
                    <div class="modal-header bg-warning text-white">
                        <h5 class="modal-title">@context.Title</h5>
                        <button type="button" class="close" aria-label="Close" @onclick="context.Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <CascadingValue Value="@context">
                            @context.Content
                        </CascadingValue>
                    </div>
                </div>
            </div>
        </div>
    </ModalTemplate>
</BlazoredModal>
```

### CODE REVIEW

**Comment by chrissainty** [comment]
That's an interesting addition @dfkeenan. I'm just about to merge some work I've done to move over to a cascading value (#173) Unfortunately that will break what you've done here. 

Would you be ok to wait until I've done that and then refactor this into the new design?

**Comment by dfkeenan** [comment]
> Would you be ok to wait until I've done that and then refactor this into the new design?

Sure, that's fine @chrissainty . I will attempt to get it going once your changes are merged.

**Comment by chrissainty** [comment]
@dfkeenan My work is now merged.

**Comment by dfkeenan** [comment]
I added a `ModalTemplate` parameter to `CascadingBlazoredModal`. It seems to work but it is currently affecting the whole site because you have put the `CascadingBlazoredModal` in the `App`. Not sure how to demonstrate it just on one page. Unless I move the `CascadingBlazoredModal` to the layout page instead. 

Or totally change how this is being done. For example have a component  you can declare else where in the tree that adds the `ModalTemplate` from that branch of the render tree down.

**Comment by chrissainty** [comment]
Closing as way out of date and we have since come up with a different solution for this problem.

**Comment by chrissainty** [comment]
Closing as way out of date and we have since come up with a different solution for this problem.

**Pull request closed without merging**
