### PR TITLE
Clarify Custom Style Wiki and Samples

### PR DESCRIPTION
**Pull request by aterbo**
Per Issue #361, this PR updates the Wiki to include information on the CSS parameters that are necessary when using a custom class to avoid some of the issues identified (no z-height, misaligned headers, no styling). It also updates the samples to better show the effect of custom styles using CSS. As part of the update of the samples, a more clearly named CSS class is used (`my-custom-modal-class` vs `blazored-prompt-dialog`) and removed unused styles in the examples.

### CODE REVIEW

**Comment by larsk2009** [comment]
Thanks @aterbo, I think this is a great addition! I am not sure if we are updating the docs folder anymore. If we are, can you also have a look at updating that? @chrissainty do we still keep the docs up to date in that folder?

**Comment by aterbo** [comment]
@larsk2009 I'm happy to update the Docs. I missed that the first time around. I'll update the PR when I get a minute.

**Comment by chrissainty** [comment]
@aterbo No we're not using the docs folder anymore so don't worry about updating any of that. @larsk2009 maybe we should get that folder removed to avoid confusion in the future.

**Comment by larsk2009** [comment]
Yeah should definitely remove it (in a seperate PR offcourse :wink:)

**Comment by aterbo** [comment]
@larsk2009  I went ahead and submitted another PR doing so. I actually did a bit of searching in the repo, and it looks like that issue has come up in the past, but always as a side conversation and never as a direct issue. Looks like it just slipped through a few times. Hope the other PR can resolve it. Deleting documentation files is easier than adding them :)

**Comment by larsk2009** [comment]
Great @aterbo!

**Review by chrissainty — APPROVED** [review]

**Comment by chrissainty** [comment]
Thanks for this @aterbo. Doc updates are always appreciated.

**Pull request merged**
