### PR TITLE
Set up key to BlazoredModalInstance component to get proper updates

### LINKED ISSUE #366: [Bug] UI is not properly updated when modal windows are closed not in reverse order
**Describe the bug**
When 2 modal windows are opened with different modal options and you close the one that was opened the first, remained second modal keep its content but gets modal options from the first window. 

**To Reproduce**
1. Prepare component that can display given text (text widget);
2. Show modal window in left-top corner with text widget with content 'Left';
2. Show second modal window in right-bottom corner with text widget with content 'Right';
3. Close first modal window that displayed in left-top corner. (I do it progromatically);
4. Modal window in right-bottom corner disappers. Modal window in left-top corner hosts text widget with content 'Right';

**Expected behavior**
Modal window in left-top corner is closed. Modal window in right-bottom corner is remained and contains text widget with content 'Right'

**Screenshots**
BlazoredModalUpdateIssue

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Discovered on Blazor Server mode, but I suppose it should work the same in Blazor WebAssembly mode

**Additional context**
Sample project. Click simulate button to see behavior.
[BlazorModalUpdateIssue.zip](https://github.com/Blazored/Modal/files/7729191/BlazorModalUpdateIssue.zip)

Simulation code extract:
```csharp
private async Task Simulate()
{
    var p1 = new ModalParameters();
    p1.Add("Text", "Left");
    var refLeftModal = ModalService.Show<TextWidget>("Left", p1, new ModalOptions { Position = ModalPosition.TopLeft });
    await Task.Delay(1000);
    var p2 = new ModalParameters();
    p2.Add("Text", "Right");
    var refRightModal = ModalService.Show<TextWidget>("Right", p2, new ModalOptions { Position = ModalPosition.BottomRight });
    await Task.Delay(1000);
    refLeftModal.Close();
}
```

### PR DESCRIPTION
**Pull request by crui3er**
Closes #366

Setting key to BlazoredModalInstance to preserv BlazoredModalInstance elements while rendering a list.
See for details https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#use-key-to-control-the-preservation-of-elements-and-components

### CODE REVIEW

**Comment by larsk2009** [comment]
Might be cool to attach a similar gif as you did in the issue here, showing it is fixed! Nice work @crui3er!

**Comment by crui3er** [comment]
Hi, here is an recording how it works with the fix in the PR.
BlazoredModalUpdateIssue_fixed

**Comment by crui3er** [comment]
Hi. Can someone review it?

**Comment by chrissainty** [comment]
@crui3er I'll be taking a look at this on Friday

**Comment by chrissainty** [comment]
Looks great! We don't really need the `blazoredModalInstance_` prefix but it also doesn't hurt.

**Review by chrissainty — APPROVED** [review]

**Pull request merged**
