### PR TITLE
Fix disposal race condition

### PR DESCRIPTION
**Pull request by lofcz**
BlazoredModal implements `IAsyncDisposable`. There is no public API to know whether our `IJsObjectReference` is currently being disposed or not. This occasionally results in an unhandled throw. As we don't really care whether our calls succeeded or not in this case, I've just wrapped them all in `try, catch`.

### CODE REVIEW

**Comment by lofcz** [comment]
Fixes #481 
Feel free to try switching dependency to `BlazorModalExperimental` (nuget) to test the fix.

**Comment by SSchulze1989** [comment]
Since it is a bad practicse to catch all exceptions and we pretty much know which exception to expect at this point it would be better to only catch the ```Microsoft.JSInterop.JSException``` specifically. Also there is no need to store the exception in variable ```e``` when it is never used again:
```csharp
try
{
   /// code ...
}
catch (Microsoft.JSInterop.JSException) {}

**Comment by lofcz** [comment]
I don't see a reason to catch only a specific exception when future Blazor implementation may change, this way we are future proof.

The other comment I consider fair but NIT as the compiler emits the exact same IL and optimizes the unused var away, see Sharplab diff.

**Comment by lofcz** [comment]
@SSchulze1989 would you mind testing the branch (as simple as switching the dependency), to chceck whether this covers #481 completely?

**Comment by SSchulze1989** [comment]
1. Exception handling should always be as specific as possible. Otherwise you run into the danger of masking an actual issue with the implementation when another error occurs that you did not account for. Granted that is probably unlikely to happen in this case but on many compiler configurations this will produce a warning that should not be ignored.

2. The same reason for the unused variable is that this as well produces an unnecessary warning. I prefer to keep my code clear of any warnings as far as possible to 0 - so that when a warning for an actual issue appears I do not overlook it.

Granted these are personal preferences you may as well ignore them - but they are in line with common best practices in most programming languages.

**Comment by SSchulze1989** [comment]
@lofcz i did some preliminary testing and did not see the issue reoccur.

**Comment by lofcz** [comment]
It actually seems like we can implement the pattern mentioned in the top answer here: https://stackoverflow.com/questions/74928714/blazor-component-removed-from-dom-before-disposal-causes-js-interop-to-fail
to never raise the error in the first place, .net7+ only.

**Comment by lofcz** [comment]
@chrissainty how would you prefer this to be addressed? Upstream has to support .NET 6 so I could hack in the approach mentioned above with conditional compiling but that would mess up the otherwise clean code.

**Comment by chrissainty** [comment]
@lofcz I haven't had a chance to look into this myself yet, only do a bit of quick research. 

Currently, I'm not convinced that the proposed solution is correct. In the linked SO post, there is a link to a GitHub issue (https://github.com/dotnet/aspnetcore/issues/45777) where MutationObserver is mention as the correct way to handle disposing of certain JS related code. I need to look into this a bit more. 

Also in the original issue (#481) it mentions JS calls to Focus Trap, we don't use JS for the focus trap. Also the clear body styles function mentioned doesn't exist either in our JS. So there are a lot of questions for me right now that need answering before picking a solution.

**Pull request closed without merging**
