### PR TITLE
Exposes OnClose event for modal

### LINKED ISSUE #2: Fire event back to calling page component.
in this case  on button click it will show the modal window but how can we send back event from modal to this page.
let's consider  on button click a modal will open where we added a new movie now we need to refresh the page to show the newly  added movie.

```csharp
@page "/"
@inject IModalService Modal

<h1>Hello, world!</h1>

Welcome to Blazored Modal.

<button onclick="@(() => Modal.Show("My Movies", typeof(Movies)))" class="btn btn-primary">
View Movies
</button>
```

### PR DESCRIPTION
**Pull request by chrissainty**
Fixes #2 

This PR correctly fires the OnClose event on the ModalService when the modal closes. Developers can now attach a handler to this event and it will be called when the modal closes.

### CODE REVIEW

**Comment by iAmBipinPaul** [comment]
How can we  pass the parameter to the modal window and get some some value in return?

Like if I  want to edit some movie, I will pass the id and modal view will get the data from the some api to edit on success it may return true on fail it may return false or it may return some T type.

**Comment by chrissainty** [comment]
Currently that's not supported. 

In the short term, if you added something via the modal you could check if there is new data by reacting to the OnClose event.  

So, for example, you would call the modal passing in your `AddMovie` component. That component would be responsible for persisting the data somewhere (API). When the modal closes you could then make a call to get the newly added movie. 

Obviously this is not ideal but will work for now.

**Comment by chrissainty** [comment]
@iAmBipinPaul I've just updated the package to support passing parameters to the modal component.

**Comment by iAmBipinPaul** [comment]
Awesome 👍

**Pull request merged**
